### ISSUE TITLE
Validation of 3.0.3 schema fails

### ISSUE THREAD

**Issue by andig** [getkin/kin-openapi#1079]
Validation fails for this file but is fine in https://oas-validation.com/. 

    bad data in "#/components/parameters/soc" (expecting ref to schema object)

Parameters:

```yaml
    soc:
      name: soc
      description: SOC in %
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/Soc"
```

Schemas:

```yaml
    Soc:
      description: SOC in %
      type: number
      example: 60
      minimum: 0
      maximum: 100
```

It's unclear to me what could be the root cause- the schema object seems to exist?

[rest-api.yaml.txt](https://github.com/user-attachments/files/20862107/rest-api.yaml.txt)

Refs https://github.com/evcc-io/docs/issues/823
