### ISSUE TITLE
Paths ending with an extension aren't matched

### ISSUE THREAD

**Issue by dunglas** [getkin/kin-openapi#129]
When using the router, the following definition is matched properly (the corresponding route is found):

```
paths:
  '/books/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    get:
      # ...
```

But this doesn't:

```
paths:
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
  '/books/{id}.json':
    get:
      # ...
```
