### ISSUE TITLE
Empty scopes is invalid for OpenAPI 3

### ISSUE THREAD

**Issue by tuzkov** [getkin/kin-openapi#133]
If I specify a empty map for oauth2 scopes, for example:
```
components:
  securitySchemes:
    auth:
      type: oauth2
      flows:
        password:
          tokenUrl: /auth/oauth2/beta1/token
          scopes: {}
```
than I got an error when call validate: 
`Error when validating Components: Security scheme 'flow' is invalid: An OAuth flow is missing 'scopes'`
but I should not.
