### ISSUE TITLE
SwaggerLoader doesn't process $ref fragments

### ISSUE THREAD

**Issue by disposedtrolley** [getkin/kin-openapi#167]
Hello!

`SwaggerLoader` doesn't seem to process fragments in `$ref` URLs. For example, if I have a ref to an external YAML file containing a fragment (#):

```yaml
get:
  operationId: findAllDefinitions
  summary: Retrieve all definitions
  responses:
    "200":
      content:
        application/json:
          examples:
            default:
              $ref: ../../Schemas/DefinitionObject.yaml#example
```

which points to `DefinitionsObject.yaml`:

```yaml
properties:
  latest:
    type: string
    description: The latest version for this definition
  owner:
    type: string
    description: The owner of the repository
  repository:
    type: string
    description: The repository of this definition
  size:
    format: int64
    type: integer
    description: The size of the whole OpenAPI file
  updated_at:
    format: date-time
    type: string
    description: The time when the file updated last
example:
  latest: 3948abef12
  owner: foo
  repository: bar
  size: 310
  updated_at: 2020-01-10 10:10:10
```

SwaggerLoader returns an error saying `expected prefix '#/components/examples/' in URI '#example'`.

There seems to be a check in the `resolveComponent()` method which generates the error if it doesn't think the correct prefix is used in the path, but it doesn't take into account URL fragments. https://github.com/getkin/kin-openapi/blob/master/openapi3/swagger_loader.go#L259

```go
if !strings.HasPrefix(ref, prefix) {
		err := fmt.Errorf("expected prefix '%s' in URI '%s'", prefix, ref)
		return nil, "", nil, err
	}
```
