### ISSUE TITLE
Issue with nullable and set operations

### ISSUE THREAD

**Issue by romain-intel** [getkin/kin-openapi#168]
I think I have found a bug in the way the ```nullable``` keyword is handled in combination with set operations (for example ```anyOf```)

As an example:
```
SomeComponentType:
  - foo:
      nullable: true
      anyOf:
        - type: array
           ...
        - type: array
```

This doesn't validate for an object that has ```foo``` with a value of ```null```. Looking at the code, it seems that it calls visitSetOperations (schema.go:610) -- which fails since null doesn't match any of the array types --, before checking for null on line 616.

I then tried a hack of adding another nullable to one of the types within the ```anyOf```.
Interestingly, this sorta worked in so much as it passed ```visitSetOperations``` but then failed in the call on line 616 (since it sees that the type of the value is null and tries to check if the ```anyOf``` schema is nullable.

So finally, the workaround I have is to add the nullable type to one of the types within the ```anyOf``` and also adding the nullable attribute to the ```anyOf``` schema itself so it looks something like this:
```
SomeComponentType:
  - foo:
      nullable: true
      anyOf:
        - type: array
           nullable: true
           ...
        - type: array
```

I am not an expert on the schema so I am not sure if the solution of moving the nil case check up to the initial switch on line 597 (from line 616) would work and not break anything but it would simplify this convoluted way of specifying that something can be one of x, y or null :).

If this is the way it is *supposed* to be specified, feel free to close this issue. Happy to submit a PR if the solution presented above does not present any downside.
