### ISSUE TITLE
Erroneous Schema.Properties with with numeric key 

### ISSUE THREAD

**Issue by chemidy** [getkin/kin-openapi#297]
I'm using an external API with an openapi like that :

```yaml
            a:
              type: object
              properties:
                25.0:
                  type: number
                  example: 1222.0
                50.0:
                  type: number
                  example: 1223.0
                75.0:
                  type: number
                  example: 1224
```

I receive this json as response

```json

{
"a":{
    "25.0": 1222.0,
    "50.0": 1223.0,
    "75.0": 1224.0
   }
}
```

But if i'm parsing the scema with kin-openapi, i show bad values  in schema.Properties string 25 instead of 25.0 for example.
I bet there is an implicit conversion to string ?

```go
fmt.Printf("hello : %+v \n", schema.Properties)

hello : map[25:0xc0001f59c0 50:0xc0001f5aa0 75:0xc0001f5b80] 
```

Instead of : 

```go
fmt.Printf("hello : %+v \n", schema.Properties)

hello : map[25.0:0xc0001f59c0 50.0:0xc0001f5aa0 75.0:0xc0001f5b80] 
```

If i'm updating the schema like that it's ok.

```yaml
            a:
              type: object
              properties:
                '25.0':
                  type: number
                  example: 1222.0
               '50.0':
                  type: number
                  example: 1223.0
                '75.0':
                  type: number
                  example: 1224
```
