### ISSUE TITLE
Problem with server url using variables with new routers

### ISSUE THREAD

**Issue by RiccardoManfrin** [getkin/kin-openapi#335]
Ciao,

I've updated to >0.50 (using gorilla mux), and it is not validating specs with this syntax because of the second url colon:

```
servers:
  - url: /
    description: devmode
  - url: '{protocol}://{server}/{prefix}/'
    description: production
    variables:
      protocol:
        enum:
          - 'http'
          - 'https'
        default: 'https'
        description: Protocol (http/https)
      server:
        default: 123z456789y0
        description: Server IP / Hostname
      prefix:
        default: ''
        description: Service platform prefix
```
Specifically [this line](https://github.com/getkin/kin-openapi/blob/master/routers/gorillamux/router.go#L36)  is failing with this error:

     "first path segment in URL cannot contain colon"

Presumibly `url.Parse` is possibly not working when variables are included in the url path (since it's possibly not anymore a URL according to RFC).
