### ISSUE TITLE
`openapi3gen` Generate multiple interdependent schemas 

### ISSUE THREAD

**Issue by austince** [getkin/kin-openapi#427]
Is there a way to generate schemas from Go types that are interdependent? 

For example:
```go
type TypeMeta struct {
	Kind string `json:"kind,omitempty"`
	APIVersion string `json:"apiVersion,omitempty"`
}

type ObjectMeta struct {
	Name string `json:"name,omitempty"`
}

type Job struct {
	TypeMeta `json:""`
	Metadata ObjectMeta `json:"metadata"`
}

func main() {
  gen := openapi3gen.NewGenerator()
  jobRef, _ := gen.GenerateSchemaRef(reflect.TypeOf(Job{}))
  objmetaRef, _ := gen.GenerateSchemaRef(reflect.TypeOf(ObjectMeta{}))
  typemetaRef, _ := gen.GenerateSchemaRef(reflect.TypeOf(TypeMeta{}))
  // ... add to a full spec's schemas ...
}

```

Results in something like:
```yaml
components:
  schemas:
    Job:
      $ref: Job
    ObjectMeta:
      $ref: ObjectMeta
    TypeMeta:
      $ref: TypeMeta
```

If I empty the `ref.Ref` field, the result embeds each schema:
```
components:
  schemas:
    Job:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          properties:
            name:
              type: string
# ...
```

Ideally, when sharing the same generator these should be able to cross-reference each other. Is there a different approach that I'm missing?
