### ISSUE TITLE
minItems enforced although array is not defined

### ISSUE THREAD

**Issue by cboitel** [getkin/kin-openapi#644]
Suppose you have a schema like:
```yaml
type: object
properties:
   strings:
       type: array
       items: 
          type: string
          minItems: 1
```

This would mean we expect:
1. an object which **may** contain a property named `strings`
2. if provided, `strings` would be an array of string values with at least 1 entry in it

As of today kin-openapi will consider an empty object (with no `strings` property) as invalid stating `strings` does not respect minItems.

I traced down the issue  in [visitJSONArray](https://github.com/getkin/kin-openapi/blob/ac1811368b118e6c46fa9eede7541c9c949ec4f8/openapi3/schema.go#L1350):
- it receives an array of interfaces
- when receiving a nil array, len will return 0 which does not respect minItems

I will submit a PR that will test if array is nil and return  nil (no error) in such case. Tests will be added too.
