### ISSUE TITLE
The error type is lost in oneOf

### ISSUE THREAD

**Issue by micronull** [getkin/kin-openapi#657]
If a field must satisfy multiple rules described using `oneOf`, we cannot get `openapi3.SchemaError` types. 
The only thing we will get is a string. 

```
components:
  schemas:
    Something:
      type: object
      properties:
        field:
          title: Some field
          oneOf:
            - title: First rule
              type: string
              minLength: 10
              maxLength: 10
            - title: Second rule
              type: string
              minLength: 15
              maxLength: 15
```

Get the error type `errorString`.
