### ISSUE TITLE
Message of the error type in required fields contains "or not to be present"

### ISSUE THREAD

**Issue by micronull** [getkin/kin-openapi#666]
Spec:
```yml
components:
  schemas:
    Something:
      type: object
      required: [field]
      properties:
        field:
          title: Some field
          type: string
```

We send incorrect type value: 
```go
err := doc.Components.Schemas["Something"].Value.VisitJSON(map[string]interface{}{"field": 123})
```
 and get an error `Error at "/field": Field must be set to string or not be present`.

This is critical case for us, since the error message must strictly follow the specification.
We return it to our customers.
