### ISSUE TITLE
Errors in `oneOf` not contain path

### ISSUE THREAD

**Issue by micronull** [getkin/kin-openapi#676]
spec:
```yaml
components:
  schemas:
    Something:
      type: object
      properties:
        first:
          type: object
          properties:
            second:
              type: object
              properties:
                third:
                  oneOf:
                   - title: First rule
                     type: string
                     minLength: 5
                     maxLength: 5
                   - title: Second rule
                     type: string
                     minLength: 10
                     maxLength: 10
```

request:
```go
err = doc.Components.Schemas["Something"].Value.VisitJSON(map[string]interface{}{
		"first": map[string]interface{}{
			"second": map[string]interface{}{
				"third": "123456789",
			},
		},
	})
```

We get an error that does not contain: `Error at "/first/second/third"`.
And `JSONPointer` does not return the slice.
