### ISSUE TITLE
lost format error path

### ISSUE THREAD

**Issue by micronull** [getkin/kin-openapi#681]
Line format errors no longer contain "Error at".

```yml
components:
  schemas:
    Something:
      type: object
      properties:
        ip:
          type: string
          format: ipv4
```

```go
err = doc.Components.Schemas["Something"].Value.VisitJSON(map[string]interface{}{
		`ip`: `123.0.0.11111`,
	})
```

Error: `Not an IP address`
Must be: `Error at "/ip": Not an IP address`
