### ISSUE TITLE
Distinguish between schema field zero values and undefined values.

### ISSUE THREAD

**Issue by crunk1** [getkin/kin-openapi#787]
Is there a way to distinguish between field values that are zero values (but explicitly defined) vs undefined values?

As an example, consider these two schemas:
```yaml
components:
  schemas:
    foo:
      type: string
      nullable: false
    bar:
      type: string
```

Both foo's and bar's `openapi3.Schema` values  will have `Nullable` fields set to `false`, obscuring whether the field was explicitly set to `false` or just undefined. This obviously goes for all other fields as well.

My use case: I'm creating our own type generation tool which merges a schema and its `allOf` references into a single Go type (a la inheritance or composition). I'm trying to figure out the best way to handle disparities between fields in the schema and the `allOf` references. e.g. a schema has `nullable: false` but a schema it "imports" in its `allOf` says `nullable: true`.
