### ISSUE TITLE
Validating OneOf in query params always matches each schema

### ISSUE THREAD

**Issue by ju-zp** [getkin/kin-openapi#789]
When use oneOf in the query schema validation will always fail due to the given value matching all of the schemas, even if it doesn't match them at all.

As an example, this schema:
```
paths:
  /items:
    get:
      description: Returns a list of stuff
      parameters:
      - description: test object
        explode: false
        in: query
        name: test
        required: true
        schema:
          type: string
          oneOf:
            - pattern: '\babc\b'
            - pattern: '\bfoo\b'
            - pattern: '\bbar\b'
``` 

Example request:
```
/items?test=abc
/items?test=def
/items?test=foo bar
``` 
Given the example requests above, all of them fail with the same error message "parameter \"test\" in query has an error: decoding oneOf failed: 3 schemas matched". It seems that they will always match each pattern regardless.
