### ISSUE TITLE
Request validation does not work correctly with anyOf

### ISSUE THREAD

**Issue by evgenykireev** [getkin/kin-openapi#83]
### Problem

Given schema
```yml
anyOf:
  - type: object
    properties:
      prop1:
        type: string
        enum:
          - Dingo
          - Husky
  - type: object
    properties:
      prop2:
        type: string
```

payload
```json
{
    "prop1": "val"
}
```
will pass validation, although should fail.

Also noticed, same payload will fail against
```yml
type: object
required:
  - prop1
properties:
  prop1:
    type: string
    enum:
      - Dingo
      - Husky

```

**Comment by fenollp** [comment]
Isn't this because second part of anyOf does not have `additionalProperties: false` thus it allows the given payload?

**Comment by evgenykireev** [comment]
@fenollp Same result for
```yml
anyOf:
  - type: object
    additionalProperties: false
    properties:
      prop1:
        type: string
        enum:
          - Dingo
          - Husky
  - type: object
    additionalProperties: false
    properties:
      prop2:
        type: string
```
